// flow-typed signature: 41e2ce468f1caa0ac867bf44dabcd6cf
// flow-typed version: <<STUB>>/repl_v^0.1.3/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'repl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'repl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'repl/lib/repl' {
  declare module.exports: any;
}

declare module 'repl/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'repl/index' {
  declare module.exports: $Exports<'repl'>;
}
declare module 'repl/index.js' {
  declare module.exports: $Exports<'repl'>;
}
declare module 'repl/lib/repl.js' {
  declare module.exports: $Exports<'repl/lib/repl'>;
}
declare module 'repl/test.js' {
  declare module.exports: $Exports<'repl/test'>;
}
