// flow-typed signature: 35cb0ac75bcde7b3513890122e564fc0
// flow-typed version: <<STUB>>/repl-promised_v^0.1.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'repl-promised'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'repl-promised' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'repl-promised/index' {
  declare module.exports: $Exports<'repl-promised'>;
}
declare module 'repl-promised/index.js' {
  declare module.exports: $Exports<'repl-promised'>;
}
